server:
  port: 4000

#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://aurora-eureka:2000/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: aurora-portal-admin
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portal?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    druid:
      # 初始化大小、最小、最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 获取连接等待超时的时间
      max-wait: 60000
      # 隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      # 1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间
      # async-init: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
#    lettuce:
#      pool:
#        max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 50 # 连接池中的最大空闲连接
#        min-idle: 10 # 连接池中的最小空闲连接
#    timeout: 1000ms


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.shimh.aurora.portal.admin.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
info:
  app:
    name: ${spring.application.name}
    description: 集中权限管理平台

# 单点登录
passport:
  clientName: aurora-portal-admin
  filterChainDefinition:
    "[/actuator/**]": anon

logging:
  level:
    org.apache.shiro: debug
